package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer addressId;
	private Users users;
	private String street;
	private String zipcode;
	private String city;
	private Set<PurchaseOrder> purchaseOrdersForBillToAddressId = new HashSet<PurchaseOrder>(0);
	private Set<PurchaseOrder> purchaseOrdersForShipToAddressId = new HashSet<PurchaseOrder>(0);

	public Address() {
	}

	public Address(Users users, String street, String zipcode, String city) {
		this.users = users;
		this.street = street;
		this.zipcode = zipcode;
		this.city = city;
	}

	public Address(Users users, String street, String zipcode, String city,
			Set<PurchaseOrder> purchaseOrdersForBillToAddressId, Set<PurchaseOrder> purchaseOrdersForShipToAddressId) {
		this.users = users;
		this.street = street;
		this.zipcode = zipcode;
		this.city = city;
		this.purchaseOrdersForBillToAddressId = purchaseOrdersForBillToAddressId;
		this.purchaseOrdersForShipToAddressId = purchaseOrdersForShipToAddressId;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set<PurchaseOrder> getPurchaseOrdersForBillToAddressId() {
		return this.purchaseOrdersForBillToAddressId;
	}

	public void setPurchaseOrdersForBillToAddressId(Set<PurchaseOrder> purchaseOrdersForBillToAddressId) {
		this.purchaseOrdersForBillToAddressId = purchaseOrdersForBillToAddressId;
	}

	public Set<PurchaseOrder> getPurchaseOrdersForShipToAddressId() {
		return this.purchaseOrdersForShipToAddressId;
	}

	public void setPurchaseOrdersForShipToAddressId(Set<PurchaseOrder> purchaseOrdersForShipToAddressId) {
		this.purchaseOrdersForShipToAddressId = purchaseOrdersForShipToAddressId;
	}

}
