package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private String username;
	private Users users;
	private String authority;

	public Authorities() {
	}

	public Authorities(Users users, String authority) {
		this.users = users;
		this.authority = authority;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
