package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import mx.com.mentoringit.model.dto.InventoryDTO;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer bookId;
	private Category category;
	private String title;
	private String description;
	private float listPrice;
	private String listPriceCurrency;
	private Float paperback;
	private String publisher;
	private String language;
	private String isbn10Integer;
	private String isbn13Integer;
	private Set<BookImage> bookImages = new HashSet<BookImage>(0);
	private Inventory inventory;
	private Set<LineItem> lineItems = new HashSet<LineItem>(0);
	private Set<Author> authors = new HashSet<Author>(0);

	public Book() {
	}

	public Book(Category category, String title, float listPrice, String listPriceCurrency) {
		this.category = category;
		this.title = title;
		this.listPrice = listPrice;
		this.listPriceCurrency = listPriceCurrency;
	}

	public Book(Category category, String title, String description, float listPrice, String listPriceCurrency,
			Float paperback, String publisher, String language, String isbn10Integer, String isbn13Integer,
			Set<BookImage> bookImages, Inventory inventory, Set<LineItem> lineItems, Set<Author> authors) {
		this.category = category;
		this.title = title;
		this.description = description;
		this.listPrice = listPrice;
		this.listPriceCurrency = listPriceCurrency;
		this.paperback = paperback;
		this.publisher = publisher;
		this.language = language;
		this.isbn10Integer = isbn10Integer;
		this.isbn13Integer = isbn13Integer;
		this.bookImages = bookImages;
		this.inventory = inventory;
		this.lineItems = lineItems;
		this.authors = authors;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(float listPrice) {
		this.listPrice = listPrice;
	}

	public String getListPriceCurrency() {
		return this.listPriceCurrency;
	}

	public void setListPriceCurrency(String listPriceCurrency) {
		this.listPriceCurrency = listPriceCurrency;
	}

	public Float getPaperback() {
		return this.paperback;
	}

	public void setPaperback(Float paperback) {
		this.paperback = paperback;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getIsbn10Integer() {
		return this.isbn10Integer;
	}

	public void setIsbn10Integer(String isbn10Integer) {
		this.isbn10Integer = isbn10Integer;
	}

	public String getIsbn13Integer() {
		return this.isbn13Integer;
	}

	public void setIsbn13Integer(String isbn13Integer) {
		this.isbn13Integer = isbn13Integer;
	}

	public Set<BookImage> getBookImages() {
		return this.bookImages;
	}

	public void setBookImages(Set<BookImage> bookImages) {
		this.bookImages = bookImages;
	}

	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	public Set<LineItem> getLineItems() {
		return this.lineItems;
	}

	public void setLineItems(Set<LineItem> lineItems) {
		this.lineItems = lineItems;
	}

	public Set<Author> getAuthors() {
		return this.authors;
	}

	public void setAuthors(Set<Author> authors) {
		this.authors = authors;
	}
	
	public InventoryDTO getInventoryDTO(){
		InventoryDTO inventoryDTO = new InventoryDTO();
		
		if(inventory == null){
			inventoryDTO.setBookQuantity(0);
		}else{
			inventoryDTO.setBookQuantity(inventory.getBookQuantity());			
		}
		return inventoryDTO;
	}

}
