package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private Integer bookId;
	private Book book;
	private int bookQuantity;

	public Inventory() {
	}

	public Inventory(Book book, int bookQuantity) {
		this.book = book;
		this.bookQuantity = bookQuantity;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public int getBookQuantity() {
		return this.bookQuantity;
	}

	public void setBookQuantity(int bookQuantity) {
		this.bookQuantity = bookQuantity;
	}

}
