package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

import org.springframework.beans.BeanUtils;

import mx.com.mentoringit.model.dto.BookDTO;
import mx.com.mentoringit.model.dto.PurchaseOrderDTO;

/**
 * LineItem generated by hbm2java
 */
public class LineItem implements java.io.Serializable {

	private Integer lineItemId;
	private Book book;
	private PurchaseOrder purchaseOrder;
	private int quantity;
	private float unitPrice;

	public LineItem() {
	}


	public Integer getLineItemId() {
		return this.lineItemId;
	}

	public void setLineItemId(Integer lineItemId) {
		this.lineItemId = lineItemId;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}
	public void setBookDTO(BookDTO book){
		
		if (this.book == null)
			this.book = new Book();
		
		BeanUtils.copyProperties(book, this.book);
	}

	public PurchaseOrder getPurchaseOrder() {
		return this.purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(float unitPrice) {
		this.unitPrice = unitPrice;
	}

}
