package mx.com.mentoringit.model.entities;
// Generated 7/10/2017 06:48:09 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.BeanUtils;

import mx.com.mentoringit.model.dto.LineItemDTO;

/**
 * PurchaseOrder generated by hbm2java
 */
public class PurchaseOrder implements java.io.Serializable {

	private Integer purchaseOrderId;
	private Address addressByShipToAddressId;
	private Address addressByBillToAddressId;
	private Users users;
	private Date orderDate;
	private float totalPrice;
	private Set<LineItem> lineItems = new HashSet<LineItem>(0);

	public PurchaseOrder() {
	}

	public Integer getPurchaseOrderId() {
		return this.purchaseOrderId;
	}

	public void setPurchaseOrderId(Integer purchaseOrderId) {
		this.purchaseOrderId = purchaseOrderId;
	}

	public Address getAddressByShipToAddressId() {
		return this.addressByShipToAddressId;
	}

	public void setAddressByShipToAddressId(Address addressByShipToAddressId) {
		this.addressByShipToAddressId = addressByShipToAddressId;
	}

	public Address getAddressByBillToAddressId() {
		return this.addressByBillToAddressId;
	}

	public void setAddressByBillToAddressId(Address addressByBillToAddressId) {
		this.addressByBillToAddressId = addressByBillToAddressId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Set<LineItem> getLineItems() {
		return this.lineItems;
	}

	public void setLineItems(Set<LineItem> lineItems) {
		this.lineItems = lineItems;
	}
	public void setLineItemsDTO(Set<LineItemDTO> lineItems) {
			
		for (LineItemDTO lineItemDTO : lineItems) {
			LineItem lineItem = new LineItem();
			BeanUtils.copyProperties(lineItemDTO, lineItem);
			this.lineItems.add(lineItem);
		}
	}
	
	public Set<LineItemDTO> getLineItemsDTO(){
		Set<LineItemDTO> lineItemsDTO = new HashSet<LineItemDTO>();
		for (LineItem lineItem : lineItems) {
			LineItemDTO lineItemDTO = new LineItemDTO();
			BeanUtils.copyProperties(lineItem, lineItemDTO);
			lineItemsDTO.add(lineItemDTO);
		}
		return lineItemsDTO;
	}
}